### PR TITLE
Create PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by MikeWilliams-UK**

### CODE REVIEW

**Comment by deadlyvices** [comment]
Does this imply that all PRs must go through the web client?  Not the GitHub VS interface?  If so, fine, it's just that this restriction needs to be made clear.

**Comment by MikeWilliams-UK** [comment]
This should only be for Pull Request for "external" users

**Comment by deadlyvices** [comment]
So we've got 3 templates so far. Bug request, improvement and pull request.
Do we need one for new features?

**Comment by MikeWilliams-UK** [comment]
Wrong the three templates are PR, BUG, FEATURE

**Comment by MikeWilliams-UK** [comment]
Just getting the project up to the advised commuity standards

**Comment by deadlyvices** [comment]
Ok so I mentioned four, which means we could do with an Improvement template

**Pull request merged**
